"""add low_quality face category

Revision ID: 0a8b31b53d10
Revises: 0ba800e22028
Create Date: 2026-06-01 17:19:56.492172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a8b31b53d10'
down_revision: Union[str, Sequence[str], None] = '0ba800e22028'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute(
        "ALTER TYPE face_category ADD VALUE IF NOT EXISTS 'low_quality'"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
