"""source enum and media and media description refactoring

Revision ID: 21057320d630
Revises: 0a8b31b53d10
Create Date: 2026-06-19 16:43:10.709402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '21057320d630'
down_revision: Union[str, Sequence[str], None] = '0a8b31b53d10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    op.execute("ALTER TYPE media_source RENAME TO media_source_old")

    op.execute("""
        CREATE TYPE media_source AS ENUM (
            'in_media',
            'in_tv_news',
            'digital',
            'test_media',
            'user_upload'
        )
        """)

    op.execute("""
        ALTER TABLE media
        ALTER COLUMN source
        TYPE media_source
        USING source::text::media_source
        """)

    op.execute("DROP TYPE media_source_old")

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media', sa.Column('material_id', sa.String(), nullable=False))
    op.add_column('media', sa.Column('duration', sa.Float(), nullable=False))
    op.create_index(op.f('ix_media_material_id'), 'media', ['material_id'], unique=True)
    op.add_column('media_description', sa.Column('material_id', sa.String(), nullable=False))
    op.add_column('media_description', sa.Column('shooting_date', sa.String(), nullable=False))
    op.add_column('media_description', sa.Column('operators', sa.String(), nullable=True))
    op.add_column('media_description', sa.Column('another_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('media_description', sa.Column('source_path', sa.String(), nullable=False))
    op.add_column('media_description', sa.Column('source_hash', sa.String(length=64), nullable=True))
    op.add_column('media_description', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('media_description', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.drop_index(op.f('ix_media_description_date'), table_name='media_description')
    op.drop_index(op.f('ix_media_description_duration'), table_name='media_description')
    op.drop_index(op.f('ix_media_description_journalist'), table_name='media_description')
    op.drop_index(op.f('ix_media_description_media_id'), table_name='media_description')
    op.create_index(op.f('ix_media_description_material_id'), 'media_description', ['material_id'], unique=False)
    op.create_index(op.f('ix_media_description_shooting_date'), 'media_description', ['shooting_date'], unique=False)
    op.create_index(op.f('ix_media_description_source_hash'), 'media_description', ['source_hash'], unique=False)
    op.create_index(op.f('ix_media_description_source_path'), 'media_description', ['source_path'], unique=False)
    op.drop_constraint(op.f('media_description_media_id_fkey'), 'media_description', type_='foreignkey')
    op.drop_column('media_description', 'media_id')
    op.drop_column('media_description', 'date')
    op.drop_column('media_description', 'duration')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media_description', sa.Column('duration', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('media_description', sa.Column('date', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('media_description', sa.Column('media_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('media_description_media_id_fkey'), 'media_description', 'media', ['media_id'], ['id'])
    op.drop_index(op.f('ix_media_description_source_path'), table_name='media_description')
    op.drop_index(op.f('ix_media_description_source_hash'), table_name='media_description')
    op.drop_index(op.f('ix_media_description_shooting_date'), table_name='media_description')
    op.drop_index(op.f('ix_media_description_material_id'), table_name='media_description')
    op.create_index(op.f('ix_media_description_media_id'), 'media_description', ['media_id'], unique=False)
    op.create_index(op.f('ix_media_description_journalist'), 'media_description', ['journalist'], unique=False)
    op.create_index(op.f('ix_media_description_duration'), 'media_description', ['duration'], unique=False)
    op.create_index(op.f('ix_media_description_date'), 'media_description', ['date'], unique=False)
    op.drop_column('media_description', 'updated_at')
    op.drop_column('media_description', 'created_at')
    op.drop_column('media_description', 'source_hash')
    op.drop_column('media_description', 'source_path')
    op.drop_column('media_description', 'another_info')
    op.drop_column('media_description', 'operators')
    op.drop_column('media_description', 'shooting_date')
    op.drop_column('media_description', 'material_id')
    op.drop_index(op.f('ix_media_material_id'), table_name='media')
    op.drop_column('media', 'duration')
    op.drop_column('media', 'material_id')
    # ### end Alembic commands ###
