"""add cluster id to person

Revision ID: 466575abe357
Revises: f1b3879110e7
Create Date: 2026-04-29 17:47:06.672483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '466575abe357'
down_revision: Union[str, Sequence[str], None] = 'f1b3879110e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('cluster_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_person_cluster_id'), 'person', ['cluster_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_person_cluster_id'), table_name='person')
    op.drop_column('person', 'cluster_id')
    # ### end Alembic commands ###
