"""add media description

Revision ID: 5b796601fec2
Revises: d33b1bf91983
Create Date: 2026-04-28 12:03:13.617554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b796601fec2'
down_revision: Union[str, Sequence[str], None] = 'd33b1bf91983'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media_description',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('media_id', sa.Integer(), nullable=False),
    sa.Column('section', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('date', sa.String(), nullable=True),
    sa.Column('duration', sa.String(), nullable=True),
    sa.Column('journalist', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_media_description_date'), 'media_description', ['date'], unique=False)
    op.create_index(op.f('ix_media_description_duration'), 'media_description', ['duration'], unique=False)
    op.create_index(op.f('ix_media_description_journalist'), 'media_description', ['journalist'], unique=False)
    op.create_index(op.f('ix_media_description_media_id'), 'media_description', ['media_id'], unique=False)
    op.create_index(op.f('ix_media_description_section'), 'media_description', ['section'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_media_description_section'), table_name='media_description')
    op.drop_index(op.f('ix_media_description_media_id'), table_name='media_description')
    op.drop_index(op.f('ix_media_description_journalist'), table_name='media_description')
    op.drop_index(op.f('ix_media_description_duration'), table_name='media_description')
    op.drop_index(op.f('ix_media_description_date'), table_name='media_description')
    op.drop_table('media_description')
    # ### end Alembic commands ###
