"""update face suspicious fields

Revision ID: b6dcc84275ff
Revises: 466575abe357
Create Date: 2026-05-25 16:14:37.521371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b6dcc84275ff'
down_revision: Union[str, Sequence[str], None] = '466575abe357'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('face', sa.Column('is_suspicious', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('face', sa.Column('suspicion_reason', sa.String(), nullable=True))
    op.add_column('face', sa.Column('clip_category', sa.String(), nullable=True))
    op.add_column('face', sa.Column('clip_score', sa.Float(), nullable=True))
    op.add_column('face', sa.Column('clip_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column('face', 'person_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_face_clip_category'), 'face', ['clip_category'], unique=False)
    op.create_index(op.f('ix_face_is_suspicious'), 'face', ['is_suspicious'], unique=False)
    op.create_index(op.f('ix_face_suspicion_reason'), 'face', ['suspicion_reason'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_face_suspicion_reason'), table_name='face')
    op.drop_index(op.f('ix_face_is_suspicious'), table_name='face')
    op.drop_index(op.f('ix_face_clip_category'), table_name='face')
    op.alter_column('face', 'person_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('face', 'clip_scores')
    op.drop_column('face', 'clip_score')
    op.drop_column('face', 'clip_category')
    op.drop_column('face', 'suspicion_reason')
    op.drop_column('face', 'is_suspicious')
    # ### end Alembic commands ###
