"""add freeze path

Revision ID: c995425b0b3c
Revises: 5b796601fec2
Create Date: 2026-04-28 13:05:34.155483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c995425b0b3c'
down_revision: Union[str, Sequence[str], None] = '5b796601fec2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('freeze', sa.Column('freeze_path', sa.String(), nullable=False))
    op.create_index(op.f('ix_freeze_freeze_path'), 'freeze', ['freeze_path'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_freeze_freeze_path'), table_name='freeze')
    op.drop_column('freeze', 'freeze_path')
    # ### end Alembic commands ###
