"""init tables

Revision ID: d33b1bf91983
Revises: 
Create Date: 2026-04-23 16:35:49.569257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd33b1bf91983'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('person',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('q_code', sa.String(), nullable=True),
    sa.Column('link', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('public', 'non_public', 'unknown', name='person_status'), server_default=sa.text("'unknown'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cluster_tag', sa.String(), nullable=True),
    sa.Column('cluster_distance', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_person_cluster_tag'), 'person', ['cluster_tag'], unique=False)
    op.create_index(op.f('ix_person_code'), 'person', ['code'], unique=True)
    op.create_index(op.f('ix_person_name'), 'person', ['name'], unique=False)
    op.create_index(op.f('ix_person_q_code'), 'person', ['q_code'], unique=True)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('journalist', 'archivist', 'developer', 'tester', name='user_role'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_name'), 'user', ['name'], unique=True)
    op.create_table('embedding',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('embedding_type', sa.Enum('reference_face', 'detected_face', name='embedding_type'), nullable=False),
    sa.Column('source', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('vector', postgresql.ARRAY(sa.Float()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_embedding_person_id'), 'embedding', ['person_id'], unique=False)
    op.create_table('history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_history_action'), 'history', ['action'], unique=False)
    op.create_index(op.f('ix_history_user_id'), 'history', ['user_id'], unique=False)
    op.create_table('media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.Enum('in_media', 'media_teca', 'user_upload', name='media_source'), nullable=False),
    sa.Column('media_type', sa.Enum('image', 'video', name='media_type'), nullable=False),
    sa.Column('media_path', sa.String(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_media_media_path'), 'media', ['media_path'], unique=True)
    op.create_index(op.f('ix_media_media_type'), 'media', ['media_type'], unique=False)
    op.create_index(op.f('ix_media_source'), 'media', ['source'], unique=False)
    op.create_index(op.f('ix_media_user_id'), 'media', ['user_id'], unique=False)
    op.create_table('freeze',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time_in', sa.Float(), nullable=False),
    sa.Column('time_out', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('media_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_freeze_media_id'), 'freeze', ['media_id'], unique=False)
    op.create_table('iteration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('processing', 'completed', 'error', name='iteration_status'), server_default=sa.text("'processing'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('media_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_iteration_media_id'), 'iteration', ['media_id'], unique=False)
    op.create_index(op.f('ix_iteration_status'), 'iteration', ['status'], unique=False)
    op.create_index(op.f('ix_iteration_user_id'), 'iteration', ['user_id'], unique=False)
    op.create_table('face',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bbox', postgresql.ARRAY(sa.Float()), nullable=False),
    sa.Column('gender', sa.Enum('male', 'female', 'unknown', name='face_gender'), server_default=sa.text("'unknown'"), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('embedding_id', sa.Integer(), nullable=False),
    sa.Column('freeze_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('iteration_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['embedding_id'], ['embedding.id'], ),
    sa.ForeignKeyConstraint(['freeze_id'], ['freeze.id'], ),
    sa.ForeignKeyConstraint(['iteration_id'], ['iteration.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_face_confidence'), 'face', ['confidence'], unique=False)
    op.create_index(op.f('ix_face_embedding_id'), 'face', ['embedding_id'], unique=False)
    op.create_index(op.f('ix_face_freeze_id'), 'face', ['freeze_id'], unique=False)
    op.create_index(op.f('ix_face_gender'), 'face', ['gender'], unique=False)
    op.create_index(op.f('ix_face_iteration_id'), 'face', ['iteration_id'], unique=False)
    op.create_index(op.f('ix_face_person_id'), 'face', ['person_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_face_person_id'), table_name='face')
    op.drop_index(op.f('ix_face_iteration_id'), table_name='face')
    op.drop_index(op.f('ix_face_gender'), table_name='face')
    op.drop_index(op.f('ix_face_freeze_id'), table_name='face')
    op.drop_index(op.f('ix_face_embedding_id'), table_name='face')
    op.drop_index(op.f('ix_face_confidence'), table_name='face')
    op.drop_table('face')
    op.drop_index(op.f('ix_iteration_user_id'), table_name='iteration')
    op.drop_index(op.f('ix_iteration_status'), table_name='iteration')
    op.drop_index(op.f('ix_iteration_media_id'), table_name='iteration')
    op.drop_table('iteration')
    op.drop_index(op.f('ix_freeze_media_id'), table_name='freeze')
    op.drop_table('freeze')
    op.drop_index(op.f('ix_media_user_id'), table_name='media')
    op.drop_index(op.f('ix_media_source'), table_name='media')
    op.drop_index(op.f('ix_media_media_type'), table_name='media')
    op.drop_index(op.f('ix_media_media_path'), table_name='media')
    op.drop_table('media')
    op.drop_index(op.f('ix_history_user_id'), table_name='history')
    op.drop_index(op.f('ix_history_action'), table_name='history')
    op.drop_table('history')
    op.drop_index(op.f('ix_embedding_person_id'), table_name='embedding')
    op.drop_table('embedding')
    op.drop_index(op.f('ix_user_name'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_person_q_code'), table_name='person')
    op.drop_index(op.f('ix_person_name'), table_name='person')
    op.drop_index(op.f('ix_person_code'), table_name='person')
    op.drop_index(op.f('ix_person_cluster_tag'), table_name='person')
    op.drop_table('person')
    # ### end Alembic commands ###
