"""add face quality

Revision ID: f1b3879110e7
Revises: c995425b0b3c
Create Date: 2026-04-29 13:24:19.160683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1b3879110e7'
down_revision: Union[str, Sequence[str], None] = 'c995425b0b3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('face', sa.Column('quality', sa.Float(), nullable=True))
    op.create_index(op.f('ix_face_quality'), 'face', ['quality'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_face_quality'), table_name='face')
    op.drop_column('face', 'quality')
    # ### end Alembic commands ###
